#!/usr/bin/env bash
# One-time / occasional setup for RustDesk Android native builds.
# Generates flutter/.android_env.sh — source it before build/run scripts:
#   source flutter/.android_env.sh
#
# Usage:
#   ./flutter/setup_android_env.sh
#   ./flutter/setup_android_env.sh --vcpkg x86_64        # also build vcpkg deps for one ABI
#   ./flutter/setup_android_env.sh --vcpkg arm64-v8a

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_OUT="$SCRIPT_DIR/.android_env.sh"

CARGO_NDK_VERSION="${CARGO_NDK_VERSION:-3.1.2}"

die() {
	echo "setup_android_env: $*" >&2
	exit 1
}

latest_dir_under() {
	local parent="$1"
	if [[ ! -d "$parent" ]]; then
		return 1
	fi
	ls -1 "$parent" 2>/dev/null | sort -V | tail -n 1
}

detect_sdk_root() {
	if [[ -n "${ANDROID_SDK_ROOT:-}" ]]; then
		echo "$ANDROID_SDK_ROOT"
		return
	fi
	if [[ -n "${ANDROID_HOME:-}" ]]; then
		echo "$ANDROID_HOME"
		return
	fi
	local fallback="$HOME/Android/Sdk"
	if [[ -d "$fallback" ]]; then
		echo "$fallback"
		return
	fi
	return 1
}

detect_ndk_home() {
	if [[ -n "${ANDROID_NDK_HOME:-}" && -d "${ANDROID_NDK_HOME}" ]]; then
		echo "$ANDROID_NDK_HOME"
		return
	fi
	local sdk
	sdk="$(detect_sdk_root)" || return 1
	local ndk_parent="$sdk/ndk"
	local ver
	ver="$(latest_dir_under "$ndk_parent")" || return 1
	local candidate="$ndk_parent/$ver"
	if [[ -d "$candidate" ]]; then
		echo "$candidate"
		return
	fi
	return 1
}

detect_host_prebuilt() {
	local ndk="$1"
	local name
	while IFS= read -r name; do
		if [[ -d "$ndk/toolchains/llvm/prebuilt/$name" ]]; then
			echo "$name"
			return
		fi
	done <<EOF
linux-x86_64
linux-arm64
darwin-arm64
darwin-x86_64
EOF
	return 1
}

detect_vcpkg_root() {
	if [[ -n "${VCPKG_ROOT:-}" && -d "${VCPKG_ROOT}" ]]; then
		echo "$VCPKG_ROOT"
		return
	fi
	local fallback="$HOME/vcpkg"
	if [[ -d "$fallback" ]]; then
		echo "$fallback"
		return
	fi
	return 1
}

MAIN_VCPKG_ABI=""
while [[ $# -gt 0 ]]; do
	case "$1" in
	--vcpkg)
		MAIN_VCPKG_ABI="${2:-}"
		[[ -n "$MAIN_VCPKG_ABI" ]] || die "--vcpkg requires ABI (e.g. x86_64, arm64-v8a)"
		shift 2
		;;
	-h | --help)
		echo "Usage: $0 [--vcpkg <ANDROID_ABI>]"
		echo "  ANDROID_ABI: arm64-v8a | armeabi-v7a | x86_64 | x86"
		exit 0
		;;
	*)
		die "unknown argument: $1"
		;;
	esac
done

NDK_HOME="$(detect_ndk_home)" || die "Set ANDROID_NDK_HOME or install NDK under Android Sdk/ndk/"
HOST_PRE="$(detect_host_prebuilt "$NDK_HOME")" || die "Could not find llvm prebuilt under NDK"

VCPKG_HOME="$(detect_vcpkg_root)" || die "Set VCPKG_ROOT or clone vcpkg to \$HOME/vcpkg"

SDK_ROOT="$(detect_sdk_root)" || true

cat >"$ENV_OUT" <<EOF
# Generated by flutter/setup_android_env.sh — machine-local; do not commit.
export ANDROID_NDK_HOME="$(printf '%q' "$NDK_HOME")"
export ANDROID_NDK_ROOT="$(printf '%q' "$NDK_HOME")"
export ANDROID_NDK_HOST_PREBUILT="$(printf '%q' "$HOST_PRE")"
export VCPKG_ROOT="$(printf '%q' "$VCPKG_HOME")"
EOF
if [[ -n "${SDK_ROOT:-}" ]]; then
	echo "export ANDROID_SDK_ROOT=$(printf '%q' "$SDK_ROOT")" >>"$ENV_OUT"
	echo "export ANDROID_HOME=$(printf '%q' "$SDK_ROOT")" >>"$ENV_OUT"
fi

chmod 600 "$ENV_OUT" 2>/dev/null || true

echo "Wrote $ENV_OUT"
echo "Source it in your shell:"
echo "  source $ENV_OUT"

# shellcheck disable=SC1091
source "$ENV_OUT"

echo "Installing Rust Android targets..."
rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android i686-linux-android

echo "Installing cargo-ndk ${CARGO_NDK_VERSION}..."
cargo install cargo-ndk --version "${CARGO_NDK_VERSION}" --locked

if [[ -n "$MAIN_VCPKG_ABI" ]]; then
	echo "Building vcpkg manifest deps for ABI: $MAIN_VCPKG_ABI ..."
	export ANDROID_NDK_HOME ANDROID_NDK_ROOT VCPKG_ROOT
	"$SCRIPT_DIR/build_android_deps.sh" "$MAIN_VCPKG_ABI"
fi

echo "Done. Next:"
echo "  source $ENV_OUT"
echo "  cd $REPO_ROOT/flutter && ./run_android.sh -d <device>"
